[build]
  publish = "RH_frontend/web-build"  # Expo genera en web-build, no en build
  command = "cd RH_frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"  # Usa Node 18 (compatible con Expo)
  # NO configures Python aqu√≠ ya que no es necesario